# Generate each example analysis class using the current state of class templates

generate_compile_example_analysis KVIndra INDRA_camp1 ReconAnal ExampleINDRAAnalysis
generate_compile_example_analysis KVMultiDet INDRA_camp1 SimAnal ExampleSimDataAnalysis
generate_compile_example_analysis KVMultiDet INDRA_camp1 FiltAnal ExampleFilteredSimDataAnalysis
generate_compile_example_analysis KVMultiDet INDRAFAZIA RawAnal ExampleRawAnalysis
generate_compile_example_analysis KVMultiDet INDRAFAZIA RawReconAnal ExampleReconRawAnalysis
generate_compile_example_analysis KVMultiDet INDRAFAZIA ReconAnal ExampleReconAnalysis
